# Generated by Django 5.1.4 on 2024-12-06 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0008_subject_question_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quizapp.subject'),
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizapp.subject'),
        ),
    ]
